language: rust
sudo: required
rust:
  - stable
# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
cache: cargo
before_script: ((cargo install cargo-travis && cargo install rustfmt) || true)
script:
  - cd lako_interpreted
  - cargo build --verbose 
  - cargo test --verbose
after_success:
  - cargo coveralls